### ISSUE TITLE
Create POS tagged corpus

### ISSUE THREAD

**Issue by aibakeneko** [inidun/curated_courier#1]

**Comment by aibakeneko** [comment]
Config file for creating POS tagged corpus

### `courier_article.yml`

```
corpus_name: courier_unesco
corpus_pattern: '*.zip'
corpus_type: 1
language: english
pipelines:
  tagged_frame_pipeline: penelope.pipeline.pipelines.to_tagged_frame_pipeline
checkpoint_opts:
    content_type_code: 1
    sep: "\t"
    quoting: 3
    document_index_name: null
    document_index_sep: "\t"
    text_column: text
    lemma_column: lemma_
    pos_column: pos_
    extra_columns: []
    custom_serializer_classname: null
    deserialize_processes: 1
    deserialize_chunksize: 4
    feather_folder: /data/inidun/courier/corpus/v0.1.0/article_corpus.feather
    index_column: null
pipeline_payload:
  source: /data/inidun/courier/corpus/v0.1.0/article_corpus.zip
  document_index_source: /data/inidun/courier/corpus/v0.1.0/document_index.csv
  document_index_sep: "\t"
  filenames: null
  memory_store:
    lang: en
    text_column: text
    lemma_column: lemma_
    pos_column: pos_
    tagger:
      class_name: penelope.pipeline.spacy.SpacyTagger
      options:
        model: en_core_web_sm
        disable: null
        exclude: null
        keep_hyphens: false
        remove_whitespace_ents: false
        attributes: [ text, lemma_, pos_, is_punct, is_stop ]
        filters: null
    pos_schema_name: Universal
filter_opts:
  data:
    is_alpha: null
    is_digit: null
    is_punct: false
    is_stop: false
text_reader_opts:
  as_binary: false
  filename_fields:
  - "year:_:0"
  - "courier_id:_:1"
  - "record_number:_:2"
  filename_filter: null
  filename_pattern: '*.txt'
  index_field: null
  sep: "\t"
  quoting: 3
  dehyphen_expr: "\\b(\\w+)[-¬]\\s*\\r?\\n\\s*(\\w+)\\s*\\b"

```
