### ISSUE TITLE
Create DTM corpus

### ISSUE THREAD

**Issue by aibakeneko** [inidun/curated_courier#3]

**Comment by aibakeneko** [comment]
### `courier_article_dtm.yml`

```yaml
append_pos: false
config_filename: ./opts/inidun/configs/courier_article_v0.2.0.yml
input_filename: /data/inidun/courier/corpus/v0.2.0/article_corpus.feather
create_subfolder: true
deserialize_processes: 1
filename_pattern: '**/*.feather'
keep_numerals: true
keep_symbols: true
lemmatize: true
max_tokens: 2000000
max_word_length: null
min_word_length: 2
output_folder: /data/inidun/courier/dtm/v0.2.0
output_tag: article_corpus_lemma_lc
phrase: null
phrase_file: null
pos_excludes: null
pos_includes: null
pos_paddings: null
remove_stopwords: null
tf_threshold: 1
tf_threshold_mask: true
to_lower: true
```
