### ISSUE TITLE
Update DTM corpus in release `Curated Courier v1.0`

### ISSUE THREAD

**Issue by aibakeneko** [inidun/curated_courier#5]

**Comment by aibakeneko** [comment]
### `curated_courier_v1.0_dtm.yml`

```yaml
append_pos: false
config_filename: ./opts/inidun/configs/curated_courier_v1.0.yml
input_filename: /data/inidun/courier/corpus/curated_courier_v1.0/article_corpus.feather
create_subfolder: true
deserialize_processes: 1
filename_pattern: '**/*.feather'
keep_numerals: true
keep_symbols: true
lemmatize: true
max_tokens: 2000000
max_word_length: null
min_word_length: 2
output_folder: /data/inidun/courier/dtm/curated_courier_v1.0
output_tag: article_corpus_lemma_lc
phrase: null
phrase_file: null
pos_excludes: null
pos_includes: null
pos_paddings: null
remove_stopwords: null
tf_threshold: 1
tf_threshold_mask: true
to_lower: true
```
